### PR TITLE
The test provided for partial config

### LINKED ISSUE #170: Support default values for show, label, icons
Support default values for show, label, icons.  As far as I understand this test is OK, but produce error (some properties are missing).

```

  it("renders without crashing when default config", async () => {
    const el = document.createElement(CISTERN_CARD_NAME) as CardTestElement;
    el.setConfig({
      type: `custom:${CISTERN_CARD_NAME}`,
      entities: ENTITIES,
      temp: { label: "Temperature" },
      pressure: { label: "Pressure" },

    });
    el.hass = createHass();

    document.body.appendChild(el);
    await el.updateComplete;

    expect(el.shadowRoot).toBeTruthy();
    expect(el.shadowRoot!.textContent).toContain("Temperature");
    expect(el.shadowRoot!.textContent).toContain("Pressure");
  });

```

### PR DESCRIPTION
**Pull request by arufanov**
The test provided for partial config

### CODE REVIEW

File: src/types/cards.ts [hunk 1]
```diff
@@ -43,3 +43,33 @@ export interface SepticCardConfig extends LovelaceCardConfig {
 export interface SpepticCardEditorConfig extends LovelaceCardConfig {
   entities?: SepticEntitiesConfig;
 }
+
+export type ResolvedSepticItemConfig = Required<SepticItemConfig>;
+
+export interface ResolvedSepticTankConfig {
```
Comment (arufanov) [inline src/types/cards.ts]: @ren3459 I am not sure that this class is necessary. let's remove ti.

File: src/types/cards.ts [hunk 2]
```diff
@@ -43,3 +43,33 @@ export interface SepticCardConfig extends LovelaceCardConfig {
...
+  };
+  level: {
+    show: boolean;
+  };
+  scale: {
+    position: "left" | "middle";
+  };
+}
+
+export interface ResolvedSepticCardConfig extends Omit<
```
Comment (arufanov) [inline src/types/cards.ts]: @ren3459 I am not sure that this class is necessary. let's remove ti.

File: src/cards/tank-card.ts [hunk 3]
```diff
@@ -23,14 +24,12 @@ import { TANK_CARD_EDITOR_NAME, TANK_CARD_NAME } from "@/const";
 
 @customElement(TANK_CARD_NAME)
 export class TankCard extends LitElement implements LovelaceCard {
-  private _config?: SepticCardConfig;
+  private _config?: ResolvedSepticCardConfig;
```
Comment (arufanov) [inline src/cards/tank-card.ts]: @ren3459 can we work at old cotract?

**Review by arufanov — COMMENTED** [review]
@ren3459 let's fix
